# Generated by Django 2.0.1 on 2018-01-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=30)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('A', 'Authorisation'), ('P', 'Presentment')], max_length=1)),
                ('transaction_id', models.CharField(max_length=30)),
                ('merchant_mcc', models.CharField(max_length=10)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_currency', models.CharField(max_length=3)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_currency', models.CharField(max_length=3)),
                ('processed', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
