# Generated by Django 2.0.1 on 2018-01-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180117_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='base_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_currency',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
