# Generated by Django 2.0.1 on 2018-01-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180117_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
