# Generated by Django 2.0.1 on 2018-01-18 02:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180118_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_currency',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
